spring: 
  application:
    name: kdk-eureka-zuul

server: 
  port: 8100

zuul:
  routes:
    service-1:
      stripPrefix: false
      path: /api/**
      url: http://localhost:8101
    service-2:
      stripPrefix: false
      path: /python/**
      url: http://localhost:8102
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
